In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
a = np.array([23,21,19,24,35,17,18,24,33,27,21,23])
b = np.array([31,28,19,24,32,27,16,41,23,32,29,33])

In [3]:
a.mean()

23.75

In [4]:
b.mean()

27.916666666666668

In [6]:
d = b.mean() - a.mean()
d

4.166666666666668

In [7]:
np.ones(len(b))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.append(np.zeros(len(b)), np.ones(len(b)))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.])

In [40]:
sales = np.array([
    np.append(np.zeros(len(a)), np.ones(len(b))),
    np.append(a,b)
])

In [41]:
sales

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [23., 21., 19., 24., 35., 17., 18., 24., 33., 27., 21., 23., 31.,
        28., 19., 24., 32., 27., 16., 41., 23., 32., 29., 33.]])

In [42]:
sales_t = sales.T
sales_t

array([[ 0., 23.],
       [ 0., 21.],
       [ 0., 19.],
       [ 0., 24.],
       [ 0., 35.],
       [ 0., 17.],
       [ 0., 18.],
       [ 0., 24.],
       [ 0., 33.],
       [ 0., 27.],
       [ 0., 21.],
       [ 0., 23.],
       [ 1., 31.],
       [ 1., 28.],
       [ 1., 19.],
       [ 1., 24.],
       [ 1., 32.],
       [ 1., 27.],
       [ 1., 16.],
       [ 1., 41.],
       [ 1., 23.],
       [ 1., 32.],
       [ 1., 29.],
       [ 1., 33.]])

In [43]:
np.random.shuffle(sales_t)

In [44]:
sales_t

array([[ 0., 21.],
       [ 1., 29.],
       [ 0., 17.],
       [ 1., 19.],
       [ 1., 16.],
       [ 1., 32.],
       [ 0., 19.],
       [ 0., 23.],
       [ 0., 35.],
       [ 1., 33.],
       [ 0., 33.],
       [ 0., 21.],
       [ 1., 27.],
       [ 0., 27.],
       [ 1., 31.],
       [ 1., 28.],
       [ 1., 41.],
       [ 0., 23.],
       [ 1., 23.],
       [ 0., 24.],
       [ 1., 24.],
       [ 0., 24.],
       [ 0., 18.],
       [ 1., 32.]])

In [45]:
experiment_label = np.random.randint(0,2,len(sales_t))
experiment_label

array([1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1])

In [46]:
experiment_data = np.array([
    experiment_label,
    sales_t[:,1]
])
experiment_data

array([[ 1.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,
         0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.],
       [21., 29., 17., 19., 16., 32., 19., 23., 35., 33., 33., 21., 27.,
        27., 31., 28., 41., 23., 23., 24., 24., 24., 18., 32.]])

In [47]:
experiment_data_t =  experiment_data.T
experiment_data_t

array([[ 1., 21.],
       [ 1., 29.],
       [ 0., 17.],
       [ 1., 19.],
       [ 0., 16.],
       [ 0., 32.],
       [ 0., 19.],
       [ 1., 23.],
       [ 0., 35.],
       [ 0., 33.],
       [ 0., 33.],
       [ 0., 21.],
       [ 1., 27.],
       [ 0., 27.],
       [ 1., 31.],
       [ 1., 28.],
       [ 1., 41.],
       [ 1., 23.],
       [ 1., 23.],
       [ 1., 24.],
       [ 0., 24.],
       [ 1., 24.],
       [ 1., 18.],
       [ 1., 32.]])

In [48]:
experiment_data_t[experiment_data_t[:,0] == 1][:,1].mean()

25.928571428571427

In [49]:
experiment_data_t[experiment_data_t[:,0] == 0][:,1].mean()

25.7

In [57]:
def sh_exp(N):
    experiment_diff_mean = np.empty([N, 1])
    for times in np.arange(N):
        experiment_label = np.random.randint(0, 2, len(sales_t))
        experiment_data = np.array([
            experiment_label,
            sales_t[:, 1]
        ]).T
        experiment_diff_mean[times] = experiment_data[experiment_data[:,0] == 1][:1].mean() - experiment_data[experiment_data[:,0] == 0][:,1].mean()
    return experiment_diff_mean


In [54]:
def sh_exp(N):
    experiment_diff_mean = np.empty([N, 1])
    for times in np.arange(N):
        experiment_label = np.random.randint(0, 2, len(sales_t))
        experiment_data = np.array([
            experiment_label,
            sales_t[:, 1]
        ]).T
        experiment_diff_mean[times] = experiment_data[experiment_data[:, 0] == 1][:, 1].mean() - experiment_data[experiment_data[:, 0] == 0][:, 1].mean()
    return experiment_diff_mean

In [58]:
e1 = sh_exp(1000)

In [59]:
print(e1)

[[-13.5       ]
 [-10.23076923]
 [-15.61538462]
 [-14.        ]
 [-13.25      ]
 [-15.91666667]
 [-10.61538462]
 [-15.35714286]
 [-18.5       ]
 [-15.        ]
 [ -8.45454545]
 [-15.54545455]
 [-15.14285714]
 [-18.26923077]
 [-12.92307692]
 [-11.16666667]
 [-10.81818182]
 [-17.66666667]
 [-15.16666667]
 [-12.        ]
 [-15.11111111]
 [-15.16666667]
 [-15.16666667]
 [-15.        ]
 [-15.625     ]
 [-17.11111111]
 [-11.        ]
 [-13.41666667]
 [-11.58333333]
 [-17.30769231]
 [-15.77777778]
 [-14.2       ]
 [-19.22222222]
 [-10.25      ]
 [-15.        ]
 [-16.36842105]
 [-17.5       ]
 [-18.03333333]
 [-13.33333333]
 [-17.4       ]
 [-15.66666667]
 [-18.08333333]
 [-16.        ]
 [-12.66666667]
 [-14.69230769]
 [-15.875     ]
 [-12.        ]
 [-10.93333333]
 [ -8.88888889]
 [-16.5       ]
 [ -9.21428571]
 [-12.5       ]
 [ -9.75      ]
 [-10.61538462]
 [-14.1       ]
 [-16.1       ]
 [-13.75      ]
 [-12.09090909]
 [-16.83333333]
 [-17.        ]
 [-16.        ]
 [ -9.61538462]
 [-14.75

In [31]:
len(e1[e1 >= d])

0